apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pingdom-twilio-integration.fullname" . }}
  labels:
    {{- include "pingdom-twilio-integration.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | b64enc }}
