{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pingdom-twilio-integration.serviceAccountName" . }}
  labels:
{{ include "pingdom-twilio-integration.labels" . | nindent 4 }}
{{- end -}}
