apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pingdom-statuspage-integration.fullname" . }}
  labels:
    {{- include "pingdom-statuspage-integration.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pingdom-statuspage-integration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pingdom-statuspage-integration.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pingdom-statuspage-integration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "pingdom-statuspage-integration.fullname" . }}
                  key: secret
            - name: STATUSPAGE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "pingdom-statuspage-integration.fullname" . }}
                  key: statuspageToken
            - name: MAX_RETRIES
              value: {{ default "2" .Values.config.maxRetries | quote }}
            - name: RETRY_INTERVAL
              value: {{ default "10" .Values.config.retryInterval | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
